wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.15
    cli_version: 0.15.4
    framework: huggingface
    huggingface_version: 4.26.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686879593.984101
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 64
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      - 64
      3:
      - 13
      - 23
      4: 3.9.15
      5: 0.15.4
      6: 4.26.0
      8:
      - 5
      - 9
